### ISSUE TITLE
Adding whitespace to the format

### ISSUE THREAD

**Issue by neileosis** [M4sterZer0/GetSpotify-Remake#4]
It would be nice if it didn't trim off the whitespace for the output format.

So you could format it like this for example:
"{artist} - {track}         "

This helps add a gap in that improves readability when it scrolls in a loop.

Thanks!

**Comment by M4sterZer0** [comment]
Added padding options.
![Screenshot](https://i.imgur.com/RXiUIO7.png)

**Comment by M4sterZer0** [comment]
Removed padding options, fixed whitespace.
Example: ` {artist} - {track} ("{album}")`
