### ISSUE TITLE
Heading in the right direction, but...

### ISSUE THREAD

**Issue by mike9823** [M4sterZer0/GetSpotify-Remake#8]
Could you add a feature to go back to the original playlist such as my songs, or even if I was listening to todays top hits. It's great now the requests are working but after the song ends it just ends or loops that song. I have to manually go play something else. Don't know what would be best for this.

sorry i keep updating this, however I often just listen to a radio station, if you could implement something to revert back to that station after a suggestion has been played that would be perfect. If possible. If not, this app is still incredible and I have to give it to you it's amazing bro.

**Comment by M4sterZer0** [comment]
Which original playlist do you mean? You can add a playlist or a song to the background music.

![Screenshot](https://i.imgur.com/9kliL55.png)

I dont touch any Spotify playlist.

**Comment by mike9823** [comment]
Okay that's awesome, however the songs are removed once they play! Any way
to prevent that?

**Comment by M4sterZer0** [comment]
No, you can't prevent this. For what do you need it?

**Comment by mike9823** [comment]
Just to loop so I don't have to keep adding songs. But it's cool. Still an
amazing application. Thanks so much for the quick response.

**Comment by M4sterZer0** [comment]
No problem, have fun. 👍
